language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env:
        - DEPENDENCIES=""
    - php: 5.3
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 5.4
      env:
        - DEPENDENCIES=""
    - php: 5.4
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 5.5
      env:
        - DEPENDENCIES=""
    - php: 5.5
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 5.6
      env:
        - DEPENDENCIES=""
    - php: 5.6
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7.0
      env:
        - DEPENDENCIES=""
    - php: 7.0
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - TEST_COVERAGE=true
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer self-update
  - composer update $DEPENDENCIES

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - php vendor/bin/coveralls -v
